class WineOptions {
  static const List<String> types = [
    'Red',
    'White',
    'Rosé',
    'Sparkling',
    'Orange',
    'PetNat',
  ];

static final Map<String, List<String>> grapeVarietiesByType = {
  'Red': grapeVarietiesRed,
  'White': grapeVarietiesWhite,
  'Rosé': grapeVarietiesRose,
  'Sparkling': grapeVarietiesSparkling,
  'Orange': grapeVarietiesOrange,
  'PetNat': grapeVarietiesPetNat,
};

  static List<String> grapeVarietiesRed = [
    'Aglianico',
    'Areni',
    'Barbera',
    'Blaufränkisch',
    'Brachetto',
    'Brunello',
    'Cabernet Franc',
    'Cabernet Sauvignon',
    'Carignan',
    'Carménère',
    'Charbono',
    'Cinsaut',
    'Cornalin',
    'Dolcetto',
    'Gamay',
    'Gamaret',
    'Graciano',
    'Grignolino',
    'Lambrusco',
    'Malbec',
    'Merlot',
    'Montepulciano',
    'Mourverdre',
    'Monastrell',
    'Nebbiolo',
    'Negroamaro',
    "Nero d'Avola",
    'Petit Verdot',
    'Pignolo',
    'Pinot Noir',
    'Pinot Meunier',
    'Pinotage',
    'Sangiovese',
    'Syrah / Shiraz',
    'Susumaniello',
    'Trollinger',
    'Tempranillo',
    'Terret Noir',
    'Primitivo',
    'Zweigelt',
  ];
  static List<String> grapeVarietiesWhite = [
    'Arbois',
    'Arneis',
    'Chardonnay',
    'Chasselas',
    'Chenin Blanc',
    'Clairette',
    'Completer',
    'Gewürztraminer',
    'Grüner Veltliner',
    'Marsanne',
    'Müller-Thurgau',
    'Moscato',
    'Petite Arvine',
    'Petite Manseng',
    'Pinot Blanc',
    'Pinot Gris',
    'Prosecco',
    'Rauschling',
    'Riesling',
    'Roter Veltliner',
    'Roussanne',
    'Sauvignon Blanc',
    'Savagnin',
    'Sémilion',
    'Solaris',
    'Silvaner',
    'Trebbiano',
    'Verdejo',
    'Vermentino',
    'Viognier'
  ];
  static List<String> grapeVarietiesRose = [
    'Cinsaut',
    'Gamay',
    'Grenache',
    'Pinot Noir',
    'Mourvèdre',
    'Syrah',
    'Susumaniello',
    'Tempranillo',
    'Negroamaro',
    'Zweigelt'
  ];
  static List<String> grapeVarietiesSparkling = [
    'Chardonnay',
    'Pinot Noir',
    'Pinot Meunier',
    'Glera (Prosecco)',
    'Moscato',
    'Chenin Blanc',
    'Riesling',
    'Lambrusco',
    'Clairette'
  ];
  static List<String> grapeVarietiesOrange = [
    'Pinot Gris',
    'Gewürztraminer',
    'Sauvignon Blanc',
    'Savagnin',
    'Sémillon',
    'Rkatsiteli',
    'Viognier'
  ];
  static List<String> grapeVarietiesPetNat = [
    'Chenin Blanc',
    'Gamay',
    'Muscat (Moscato)',
    'Syrah',
    'Pinot Noir',
    'Grenache',
    'Riesling'
  ];
}