// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJSQCXPfjE62WM-gqPDPwAZ_kuOIgE5Rg',
    appId: '1:31090192406:web:51764bc4f6409403a64537',
    messagingSenderId: '31090192406',
    projectId: 'wiih-195a2',
    authDomain: 'wiih-195a2.firebaseapp.com',
    storageBucket: 'wiih-195a2.appspot.com',
    measurementId: 'G-V4GE5D5EPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa1TnncIlcISVhyCPMAGpa1pU2c2Wey7w',
    appId: '1:31090192406:android:f7f282fd567eb845a64537',
    messagingSenderId: '31090192406',
    projectId: 'wiih-195a2',
    storageBucket: 'wiih-195a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMoPbLbClMfDjD5QM3pjy-FiAy9cyouHc',
    appId: '1:31090192406:ios:5444303e2fb38e56a64537',
    messagingSenderId: '31090192406',
    projectId: 'wiih-195a2',
    storageBucket: 'wiih-195a2.appspot.com',
    iosClientId: '31090192406-fakfi6sp88ufg0idigfkn2vvff7irboc.apps.googleusercontent.com',
    iosBundleId: 'com.example.wiih',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMoPbLbClMfDjD5QM3pjy-FiAy9cyouHc',
    appId: '1:31090192406:ios:5444303e2fb38e56a64537',
    messagingSenderId: '31090192406',
    projectId: 'wiih-195a2',
    storageBucket: 'wiih-195a2.appspot.com',
    iosClientId: '31090192406-fakfi6sp88ufg0idigfkn2vvff7irboc.apps.googleusercontent.com',
    iosBundleId: 'com.example.wiih',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJSQCXPfjE62WM-gqPDPwAZ_kuOIgE5Rg',
    appId: '1:31090192406:web:ab16449f82e21aeea64537',
    messagingSenderId: '31090192406',
    projectId: 'wiih-195a2',
    authDomain: 'wiih-195a2.firebaseapp.com',
    storageBucket: 'wiih-195a2.appspot.com',
    measurementId: 'G-GGMXZF34P8',
  );
}
