class WineOptions {
  static const List<String> types = [
    'Red',
    'White',
    'Ros\u00E9',
    'Sparkling',
    'Orange',
    'PetNat',
  ];

  static final Map<String, List<String>> grapeVarietiesByType = {
    'Red': grapeVarietiesRed,
    'White': grapeVarietiesWhite,
    'Ros\u00E9': grapeVarietiesRose,
    'Sparkling': grapeVarietiesSparkling,
    'Orange': grapeVarietiesOrange,
    'PetNat': grapeVarietiesPetNat,
  };

  static List<String> grapeVarietiesRed = [
    'Aglianico',
    'Areni',
    'Barbera',
    'Blaufr\u00E4nkisch',
    'Bobal',
    'Brachetto',
    'Brunello',
    'Cabernet Franc',
    'Cabernet Sauvignon',
    'Carignan',
    'Carm\u00E9n\u00E8re',
    'Charbono',
    'Cinsaut',
    'Cornalin',
    'Counoise',
    'Dolcetto',
    'Dornfelder',
    'Gamaret',
    'Gamay',
    'Garnacha / Grenache',
    'Graciano',
    'Grignolino',
    'Lambrusco',
    'Malbec',
    'Mencia',
    'Merlot',
    'Mondeuse',
    'Monastrell',
    'Montepulciano',
    'Mourv\u00E8dre',
    'Nebbiolo',
    'Negroamaro',
    'Nerello Mascalese',
    'Nero d\'Avola',
    'Other',
    'Petit Verdot',
    'Pignolo',
    'Pinot Meunier',
    'Pinot Noir',
    'Pinotage',
    'Poulsard',
    'Primitivo',
    'Sangiovese',
    'Schiava',
    'Susumaniello',
    'Syrah / Shiraz',
    'Tannat',
    'Tempranillo',
    'Terret Noir',
    'Trollinger',
    'Xinomavro',
    'Zweigelt',
  ];

  static List<String> grapeVarietiesWhite = [
    'Arbois',
    'Arneis',
    'Assyrtiko',
    'Chardonnay',
    'Chasselas',
    'Chenin Blanc',
    'Clairette',
    'Completer',
    'Fiano',
    'Garganega',
    'Gew\u00FCrztraminer',
    'Gr\u00FCner Veltliner',
    'Marsanne',
    'M\u00FCller-Thurgau',
    'Moscato',
    'Other',
    'Petite Arvine',
    'Petite Manseng',
    'Pinot Blanc',
    'Pinot Gris',
    'Prosecco',
    'R\u00E4uschling',
    'Riesling',
    'Roter Veltliner',
    'Roussanne',
    'Sauvignon Blanc',
    'Savagnin',
    'S\u00E9millon',
    'Silvaner',
    'Solaris',
    'Torrontes',
    'Trebbiano',
    'Verdejo',
    'Vermentino',
    'Viognier',
    'Weissburgunder',
  ];

  static List<String> grapeVarietiesRose = [
    'Aglianico',
    'Carignan',
    'Cinsaut',
    'Gamay',
    'Grenache',
    'Mourv\u00E8dre',
    'Negroamaro',
    'Other',
    'Pinot Noir',
    'Sangiovese',
    'Susumaniello',
    'Syrah',
    'Tempranillo',
    'Zweigelt',
  ];

  static List<String> grapeVarietiesSparkling = [
    'Auxerrois',
    'Chardonnay',
    'Chenin Blanc',
    'Clairette',
    'Glera',
    'Lambrusco',
    'Macabeo',
    'Moscato',
    'Other',
    'Parellada',
    'Pinot Blanc',
    'Pinot Meunier',
    'Pinot Noir',
    'Riesling',
    'Xarel-lo',
  ];

  static List<String> grapeVarietiesOrange = [
    'Chardonnay',
    'Friulano',
    'Gew\u00FCrztraminer',
    'Malvasia',
    'Other',
    'Pinot Gris',
    'Riesling-Sylvaner',
    'Rkatsiteli',
    'Sauvignon Blanc',
    'Savagnin',
    'S\u00E9millon',
    'Viognier',
  ];

  static List<String> grapeVarietiesPetNat = [
    'Cabernet Franc',
    'Chenin Blanc',
    'Cinsaut',
    'Gamay',
    'Glera',
    'Grenache',
    'Muscat (Moscato)',
    'Other',
    'Pinot Noir',
    'Riesling',
    'Syrah',
  ];
}
